-- MySQL Workbench Synchronization
-- Generated: 2019-11-12 10:57
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: oscar

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

ALTER TABLE `avplushost`.`pacientes_afiliados` 
ADD COLUMN `forma` VARCHAR(45) NULL DEFAULT NULL AFTER `plan`,
ADD COLUMN `marca` VARCHAR(45) NULL DEFAULT NULL AFTER `forma`,
ADD COLUMN `lente` VARCHAR(45) NULL DEFAULT NULL AFTER `marca`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
